dependencies:
  - base >= 4.7 && < 5
  - transformers
  - megaparsec
  - parser-combinators
  - prettyprinter ^>=1.7.1
  - prettyprinter-ansi-terminal ^>=1.1.3
  - haskeline >=0.8.1.2
  - text
  - containers
  - tuple
  - random
  - bytestring
  - serialise
  - zlib
  - scientific
  - directory
  - mtl
  - time

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  hi:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hw3

tests:
  hw3-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hw3